// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package edu.tulane.geolocate;


public class FindWaterBodiesWithinLocalityResponse {
    protected edu.tulane.geolocate.ArrayOfString findWaterBodiesWithinLocalityResult;
    
    public FindWaterBodiesWithinLocalityResponse() {
    }
    
    public FindWaterBodiesWithinLocalityResponse(edu.tulane.geolocate.ArrayOfString findWaterBodiesWithinLocalityResult) {
        this.findWaterBodiesWithinLocalityResult = findWaterBodiesWithinLocalityResult;
    }
    
    public edu.tulane.geolocate.ArrayOfString getFindWaterBodiesWithinLocalityResult() {
        return findWaterBodiesWithinLocalityResult;
    }
    
    public void setFindWaterBodiesWithinLocalityResult(edu.tulane.geolocate.ArrayOfString findWaterBodiesWithinLocalityResult) {
        this.findWaterBodiesWithinLocalityResult = findWaterBodiesWithinLocalityResult;
    }
}
