// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package edu.tulane.geolocate;

public interface GeolocatesvcSoap extends java.rmi.Remote {
    public edu.tulane.geolocate.Georef_Result_Set georef(edu.tulane.geolocate.LocalityDescription localityDescription, boolean hwyX, boolean findWaterbody) throws 
         java.rmi.RemoteException;
    public edu.tulane.geolocate.Georef_Result_Set georef3(java.lang.String vLocality, java.lang.String vGeography, boolean hwyX, boolean findWaterbody) throws 
         java.rmi.RemoteException;
    public edu.tulane.geolocate.Georef_Result_Set georef2(java.lang.String country, java.lang.String state, java.lang.String county, java.lang.String localityString, boolean hwyX, boolean findWaterbody) throws 
         java.rmi.RemoteException;
    public edu.tulane.geolocate.ArrayOfString findWaterBodiesWithinLocality(edu.tulane.geolocate.LocalityDescription localityDescription) throws 
         java.rmi.RemoteException;
    public edu.tulane.geolocate.GeographicPoint snapPointToNearestFoundWaterBody(edu.tulane.geolocate.LocalityDescription localityDescription, edu.tulane.geolocate.GeographicPoint WGS84Coordinate) throws 
         java.rmi.RemoteException;
    public edu.tulane.geolocate.GeographicPoint snapPointToNearestFoundWaterBody2(java.lang.String country, java.lang.String state, java.lang.String county, java.lang.String localityString, double WGS84Latitude, double WGS84Longitude) throws 
         java.rmi.RemoteException;
}
