// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package edu.tulane.geolocate;


public class Georef2 {
    protected java.lang.String country;
    protected java.lang.String state;
    protected java.lang.String county;
    protected java.lang.String localityString;
    protected boolean hwyX;
    protected boolean findWaterbody;
    
    public Georef2() {
    }
    
    public Georef2(java.lang.String country, java.lang.String state, java.lang.String county, java.lang.String localityString, boolean hwyX, boolean findWaterbody) {
        this.country = country;
        this.state = state;
        this.county = county;
        this.localityString = localityString;
        this.hwyX = hwyX;
        this.findWaterbody = findWaterbody;
    }
    
    public java.lang.String getCountry() {
        return country;
    }
    
    public void setCountry(java.lang.String country) {
        this.country = country;
    }
    
    public java.lang.String getState() {
        return state;
    }
    
    public void setState(java.lang.String state) {
        this.state = state;
    }
    
    public java.lang.String getCounty() {
        return county;
    }
    
    public void setCounty(java.lang.String county) {
        this.county = county;
    }
    
    public java.lang.String getLocalityString() {
        return localityString;
    }
    
    public void setLocalityString(java.lang.String localityString) {
        this.localityString = localityString;
    }
    
    public boolean isHwyX() {
        return hwyX;
    }
    
    public void setHwyX(boolean hwyX) {
        this.hwyX = hwyX;
    }
    
    public boolean isFindWaterbody() {
        return findWaterbody;
    }
    
    public void setFindWaterbody(boolean findWaterbody) {
        this.findWaterbody = findWaterbody;
    }
}
