// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package edu.tulane.geolocate;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class Georef2Response_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_Result_QNAME = new QName("http://www.museum.tulane.edu/webservices/", "Result");
    private static final javax.xml.namespace.QName ns1_Georef_Result_Set_TYPE_QNAME = new QName("http://www.museum.tulane.edu/webservices/", "Georef_Result_Set");
    private CombinedSerializer ns1_myGeoref_Result_Set_LiteralSerializer;
    
    public Georef2Response_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public Georef2Response_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns1_myGeoref_Result_Set_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", edu.tulane.geolocate.Georef_Result_Set.class, ns1_Georef_Result_Set_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        edu.tulane.geolocate.Georef2Response instance = new edu.tulane.geolocate.Georef2Response();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_Result_QNAME)) {
                member = ns1_myGeoref_Result_Set_LiteralSerializer.deserialize(ns1_Result_QNAME, reader, context);
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull");
                }
                instance.setResult((edu.tulane.geolocate.Georef_Result_Set)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_Result_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        edu.tulane.geolocate.Georef2Response instance = (edu.tulane.geolocate.Georef2Response)obj;
        
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        edu.tulane.geolocate.Georef2Response instance = (edu.tulane.geolocate.Georef2Response)obj;
        
        if (instance.getResult() == null) {
            throw new SerializationException("literal.unexpectedNull");
        }
        ns1_myGeoref_Result_Set_LiteralSerializer.serialize(instance.getResult(), ns1_Result_QNAME, null, writer, context);
    }
}
