// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package edu.tulane.geolocate;


public class LocalityDescription {
    protected java.lang.String localityString;
    protected java.lang.String country;
    protected java.lang.String state;
    protected java.lang.String county;
    
    public LocalityDescription() {
    }
    
    public LocalityDescription(java.lang.String localityString, java.lang.String country, java.lang.String state, java.lang.String county) {
        this.localityString = localityString;
        this.country = country;
        this.state = state;
        this.county = county;
    }
    
    public java.lang.String getLocalityString() {
        return localityString;
    }
    
    public void setLocalityString(java.lang.String localityString) {
        this.localityString = localityString;
    }
    
    public java.lang.String getCountry() {
        return country;
    }
    
    public void setCountry(java.lang.String country) {
        this.country = country;
    }
    
    public java.lang.String getState() {
        return state;
    }
    
    public void setState(java.lang.String state) {
        this.state = state;
    }
    
    public java.lang.String getCounty() {
        return county;
    }
    
    public void setCounty(java.lang.String county) {
        this.county = county;
    }
}
