// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package edu.tulane.geolocate;


public class SnapPointToNearestFoundWaterBody2Response {
    protected edu.tulane.geolocate.GeographicPoint WGS84Coordinate;
    
    public SnapPointToNearestFoundWaterBody2Response() {
    }
    
    public SnapPointToNearestFoundWaterBody2Response(edu.tulane.geolocate.GeographicPoint WGS84Coordinate) {
        this.WGS84Coordinate = WGS84Coordinate;
    }
    
    public edu.tulane.geolocate.GeographicPoint getWGS84Coordinate() {
        return WGS84Coordinate;
    }
    
    public void setWGS84Coordinate(edu.tulane.geolocate.GeographicPoint WGS84Coordinate) {
        this.WGS84Coordinate = WGS84Coordinate;
    }
}
