// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package edu.tulane.geolocate;


public class SnapPointToNearestFoundWaterBody {
    protected edu.tulane.geolocate.LocalityDescription localityDescription;
    protected edu.tulane.geolocate.GeographicPoint WGS84Coordinate;
    
    public SnapPointToNearestFoundWaterBody() {
    }
    
    public SnapPointToNearestFoundWaterBody(edu.tulane.geolocate.LocalityDescription localityDescription, edu.tulane.geolocate.GeographicPoint WGS84Coordinate) {
        this.localityDescription = localityDescription;
        this.WGS84Coordinate = WGS84Coordinate;
    }
    
    public edu.tulane.geolocate.LocalityDescription getLocalityDescription() {
        return localityDescription;
    }
    
    public void setLocalityDescription(edu.tulane.geolocate.LocalityDescription localityDescription) {
        this.localityDescription = localityDescription;
    }
    
    public edu.tulane.geolocate.GeographicPoint getWGS84Coordinate() {
        return WGS84Coordinate;
    }
    
    public void setWGS84Coordinate(edu.tulane.geolocate.GeographicPoint WGS84Coordinate) {
        this.WGS84Coordinate = WGS84Coordinate;
    }
}
