// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package edu.tulane.geolocate;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class SnapPointToNearestFoundWaterBody_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_LocalityDescription_QNAME = new QName("http://www.museum.tulane.edu/webservices/", "LocalityDescription");
    private static final javax.xml.namespace.QName ns1_LocalityDescription_TYPE_QNAME = new QName("http://www.museum.tulane.edu/webservices/", "LocalityDescription");
    private CombinedSerializer ns1_myLocalityDescription_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_WGS84Coordinate_QNAME = new QName("http://www.museum.tulane.edu/webservices/", "WGS84Coordinate");
    private static final javax.xml.namespace.QName ns1_GeographicPoint_TYPE_QNAME = new QName("http://www.museum.tulane.edu/webservices/", "GeographicPoint");
    private CombinedSerializer ns1_myGeographicPoint_LiteralSerializer;
    
    public SnapPointToNearestFoundWaterBody_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public SnapPointToNearestFoundWaterBody_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns1_myLocalityDescription_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", edu.tulane.geolocate.LocalityDescription.class, ns1_LocalityDescription_TYPE_QNAME);
        ns1_myGeographicPoint_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", edu.tulane.geolocate.GeographicPoint.class, ns1_GeographicPoint_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        edu.tulane.geolocate.SnapPointToNearestFoundWaterBody instance = new edu.tulane.geolocate.SnapPointToNearestFoundWaterBody();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_LocalityDescription_QNAME)) {
                member = ns1_myLocalityDescription_LiteralSerializer.deserialize(ns1_LocalityDescription_QNAME, reader, context);
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull");
                }
                instance.setLocalityDescription((edu.tulane.geolocate.LocalityDescription)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_LocalityDescription_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_WGS84Coordinate_QNAME)) {
                member = ns1_myGeographicPoint_LiteralSerializer.deserialize(ns1_WGS84Coordinate_QNAME, reader, context);
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull");
                }
                instance.setWGS84Coordinate((edu.tulane.geolocate.GeographicPoint)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_WGS84Coordinate_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        edu.tulane.geolocate.SnapPointToNearestFoundWaterBody instance = (edu.tulane.geolocate.SnapPointToNearestFoundWaterBody)obj;
        
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        edu.tulane.geolocate.SnapPointToNearestFoundWaterBody instance = (edu.tulane.geolocate.SnapPointToNearestFoundWaterBody)obj;
        
        if (instance.getLocalityDescription() == null) {
            throw new SerializationException("literal.unexpectedNull");
        }
        ns1_myLocalityDescription_LiteralSerializer.serialize(instance.getLocalityDescription(), ns1_LocalityDescription_QNAME, null, writer, context);
        if (instance.getWGS84Coordinate() == null) {
            throw new SerializationException("literal.unexpectedNull");
        }
        ns1_myGeographicPoint_LiteralSerializer.serialize(instance.getWGS84Coordinate(), ns1_WGS84Coordinate_QNAME, null, writer, context);
    }
}
