package org.biogeomancer.records;

public enum GeorefState {
    GEOREF_CREATED,
    GEOREF_CREATION_ERROR,
    GEOREF_POINTRADIUS_CREATED,
    GEOREF_POINTRADIUS_CREATION_ERROR,
    GEOREF_GEOMETRY_CREATED,
    GEOREF_GEOMETRY_CREATION_ERROR,
    GEOREF_COMPLETED;
}



