/**
 * Copyright 2007 University of California at Berkeley.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package org.biogeomancer.records;

public enum LocSpecState {
  LOCSPEC_CREATED, LOCSPEC_ERROR_NOT_CREATED, LOCSPEC_ERROR_FEATURE_NOT_FOUND, LOCSPEC_ERROR_OFFSET_MISSING, LOCSPEC_ERROR_OFFSET_MALFORMED, LOCSPEC_ERROR_OFFSET_NEGATIVE, LOCSPEC_ERROR_OFFSETUNIT_MISSING, LOCSPEC_ERROR_OFFSETUNIT_NOT_FOUND, LOCSPEC_ERROR_HEADING_MISSING, LOCSPEC_ERROR_HEADING_NOT_FOUND, LOCSPEC_ERROR_HEADING_MALFORMED, LOCSPEC_ERROR_HEADING_MALFORMED_NUMERICAL, LOCSPEC_ERROR_HEADINGEW_NOT_EW, LOCSPEC_ERROR_HEADINGNS_NOT_NS, LOCSPEC_ERROR_ELEVATION_MISSING, LOCSPEC_ERROR_ELEVATION_MALFORMED, LOCSPEC_ERROR_ELEVATIONUNIT_MISSING, LOCSPEC_ERROR_ELEVATIONUNIT_NOT_FOUND, LOCSPEC_ERROR_DATUM_MISSING, LOCSPEC_ERROR_DATUM_NOT_FOUND, LOCSPEC_ERROR_LATLNG_MISSING, LOCSPEC_ERROR_LAT_MISSING, LOCSPEC_ERROR_LNG_MISSING, LOCSPEC_ERROR_LAT_MALFORMED, LOCSPEC_ERROR_LNG_MALFORMED, LOCSPEC_ERROR_LAT_OUT_OF_RANGE, LOCSPEC_ERROR_LNG_OUT_OF_RANGE, LOCSPEC_ERROR_UTM_MISSING, LOCSPEC_ERROR_UTMZONE_MISSING, LOCSPEC_ERROR_UTME_MISSING, LOCSPEC_ERROR_UTMN_MISSING, LOCSPEC_ERROR_UTM_MALFORMED, LOCSPEC_ERROR_UTMZONE_MALFORMED, LOCSPEC_ERROR_UTME_MALFORMED, LOCSPEC_ERROR_UTMN_MALFORMED, LOCSPEC_ERROR_UTMZONE_MISSING_BAND_LETTER, LOCSPEC_ERROR_UTMZONE_OUT_OF_RANGE, LOCSPEC_ERROR_UTME_OUT_OF_RANGE, LOCSPEC_ERROR_UTMN_OUT_OF_RANGE, LOCSPEC_ERROR_TRS_MISSING, LOCSPEC_ERROR_SUBDIVISION_MISSING, LOCSPEC_COMPLETED;
}