/**
 * Copyright 2007 University of California at Berkeley.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package edu.tulane.geolocate;

public class Georef2 {
  protected java.lang.String country;
  protected java.lang.String state;
  protected java.lang.String county;
  protected java.lang.String localityString;
  protected boolean hwyX;
  protected boolean findWaterbody;

  public Georef2() {
  }

  public Georef2(java.lang.String country, java.lang.String state,
      java.lang.String county, java.lang.String localityString, boolean hwyX,
      boolean findWaterbody) {
    this.country = country;
    this.state = state;
    this.county = county;
    this.localityString = localityString;
    this.hwyX = hwyX;
    this.findWaterbody = findWaterbody;
  }

  public java.lang.String getCountry() {
    return country;
  }

  public java.lang.String getCounty() {
    return county;
  }

  public java.lang.String getLocalityString() {
    return localityString;
  }

  public java.lang.String getState() {
    return state;
  }

  public boolean isFindWaterbody() {
    return findWaterbody;
  }

  public boolean isHwyX() {
    return hwyX;
  }

  public void setCountry(java.lang.String country) {
    this.country = country;
  }

  public void setCounty(java.lang.String county) {
    this.county = county;
  }

  public void setFindWaterbody(boolean findWaterbody) {
    this.findWaterbody = findWaterbody;
  }

  public void setHwyX(boolean hwyX) {
    this.hwyX = hwyX;
  }

  public void setLocalityString(java.lang.String localityString) {
    this.localityString = localityString;
  }

  public void setState(java.lang.String state) {
    this.state = state;
  }
}
