/**
 * Copyright 2007 University of California at Berkeley.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package edu.tulane.geolocate;

public class Georef3 {
  protected java.lang.String vLocality;
  protected java.lang.String vGeography;
  protected boolean hwyX;
  protected boolean findWaterbody;

  public Georef3() {
  }

  public Georef3(java.lang.String vLocality, java.lang.String vGeography,
      boolean hwyX, boolean findWaterbody) {
    this.vLocality = vLocality;
    this.vGeography = vGeography;
    this.hwyX = hwyX;
    this.findWaterbody = findWaterbody;
  }

  public java.lang.String getVGeography() {
    return vGeography;
  }

  public java.lang.String getVLocality() {
    return vLocality;
  }

  public boolean isFindWaterbody() {
    return findWaterbody;
  }

  public boolean isHwyX() {
    return hwyX;
  }

  public void setFindWaterbody(boolean findWaterbody) {
    this.findWaterbody = findWaterbody;
  }

  public void setHwyX(boolean hwyX) {
    this.hwyX = hwyX;
  }

  public void setVGeography(java.lang.String vGeography) {
    this.vGeography = vGeography;
  }

  public void setVLocality(java.lang.String vLocality) {
    this.vLocality = vLocality;
  }
}
