package org.biogeomancer.records;

public enum ClauseState {
    CLAUSE_CREATED,
    CLAUSE_CREATION_ERROR,
    CLAUSE_PARSED,
    CLAUSE_PARSE_ERROR,
    CLAUSE_FEATURE_NOT_FOUND_ERROR,
    CLAUSE_POINT_RADIUS_CREATION_ERROR,
    CLAUSE_POINT_RADIUS_COMPLETED,
    CLAUSE_POLYGON_COMPLETED;
}