package org.biogeomancer.records;

public enum RecState {
    REC_CREATED,
    REC_CREATION_ERROR,
    REC_LOCALITY_EXISTS,
    REC_NO_LOCALITY_ERROR,
    REC_CLAUSES_CREATED,
    REC_NO_CLAUSES_ERROR,
    REC_LOCTYPES_FOUND,
    REC_NO_LOCTYPES_ERROR,
    REC_PARSED,
    REC_PARSE_ERROR,
    REC_GEOREFERENCE_COMPLETED,
    REC_NO_GEOREFERENCE_ERROR,
    REC_CLEARED;
}