// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package edu.tulane.geolocate;


public class FindWaterBodiesWithinLocality {
    protected edu.tulane.geolocate.LocalityDescription localityDescription;
    
    public FindWaterBodiesWithinLocality() {
    }
    
    public FindWaterBodiesWithinLocality(edu.tulane.geolocate.LocalityDescription localityDescription) {
        this.localityDescription = localityDescription;
    }
    
    public edu.tulane.geolocate.LocalityDescription getLocalityDescription() {
        return localityDescription;
    }
    
    public void setLocalityDescription(edu.tulane.geolocate.LocalityDescription localityDescription) {
        this.localityDescription = localityDescription;
    }
}
