// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package edu.tulane.geolocate;

import javax.xml.rpc.*;

public interface Geolocatesvc extends javax.xml.rpc.Service {
    public edu.tulane.geolocate.GeolocatesvcSoap getGeolocatesvcSoap() throws ServiceException;
}
