// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package edu.tulane.geolocate;


public class GeorefResponse {
    protected edu.tulane.geolocate.Georef_Result_Set result;
    
    public GeorefResponse() {
    }
    
    public GeorefResponse(edu.tulane.geolocate.Georef_Result_Set result) {
        this.result = result;
    }
    
    public edu.tulane.geolocate.Georef_Result_Set getResult() {
        return result;
    }
    
    public void setResult(edu.tulane.geolocate.Georef_Result_Set result) {
        this.result = result;
    }
}
