// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package edu.tulane.geolocate;


public class SnapPointToNearestFoundWaterBody2 {
    protected java.lang.String country;
    protected java.lang.String state;
    protected java.lang.String county;
    protected java.lang.String localityString;
    protected double WGS84Latitude;
    protected double WGS84Longitude;
    
    public SnapPointToNearestFoundWaterBody2() {
    }
    
    public SnapPointToNearestFoundWaterBody2(java.lang.String country, java.lang.String state, java.lang.String county, java.lang.String localityString, double WGS84Latitude, double WGS84Longitude) {
        this.country = country;
        this.state = state;
        this.county = county;
        this.localityString = localityString;
        this.WGS84Latitude = WGS84Latitude;
        this.WGS84Longitude = WGS84Longitude;
    }
    
    public java.lang.String getCountry() {
        return country;
    }
    
    public void setCountry(java.lang.String country) {
        this.country = country;
    }
    
    public java.lang.String getState() {
        return state;
    }
    
    public void setState(java.lang.String state) {
        this.state = state;
    }
    
    public java.lang.String getCounty() {
        return county;
    }
    
    public void setCounty(java.lang.String county) {
        this.county = county;
    }
    
    public java.lang.String getLocalityString() {
        return localityString;
    }
    
    public void setLocalityString(java.lang.String localityString) {
        this.localityString = localityString;
    }
    
    public double getWGS84Latitude() {
        return WGS84Latitude;
    }
    
    public void setWGS84Latitude(double WGS84Latitude) {
        this.WGS84Latitude = WGS84Latitude;
    }
    
    public double getWGS84Longitude() {
        return WGS84Longitude;
    }
    
    public void setWGS84Longitude(double WGS84Longitude) {
        this.WGS84Longitude = WGS84Longitude;
    }
}
